package com.gcs.ophwc.services.persistance.dao.entity;
// Generated Jun 6, 2018 7:17:41 PM by Hibernate Tools 5.2.6.Final



import javax.persistence.GeneratedValue;
import javax.persistence.Id;

/**
 * Divisions generated by hbm2java
 */
public class Divisions implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue
	private Long id;
	private String divisionName;
	private String status;
	
	private String workAmount,monthlyWorkAmount;

	public Divisions() {
	}

	public Divisions(String divisionName, String status) {
		this.divisionName = divisionName;
		this.status = status;
	}


	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getDivisionName() {
		return this.divisionName;
	}

	public void setDivisionName(String divisionName) {
		this.divisionName = divisionName;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getWorkAmount() {
		return workAmount;
	}

	public void setWorkAmount(String workAmount) {
		this.workAmount = workAmount;
	}

	public String getMonthlyWorkAmount() {
		return monthlyWorkAmount;
	}

	public void setMonthlyWorkAmount(String monthlyWorkAmount) {
		this.monthlyWorkAmount = monthlyWorkAmount;
	}

	@Override
	public String toString() {
		return "Divisions [id=" + id + ", divisionName=" + divisionName + ", status=" + status + ", workAmount="
				+ workAmount + ", monthlyWorkAmount=" + monthlyWorkAmount + "]";
	}

}
