package com.gcs.ophwc.services.persistance.dao.entity;
// Generated Jun 6, 2018 7:17:41 PM by Hibernate Tools 5.2.6.Final



import java.util.List;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;

/**
 * Divisions generated by hbm2java
 */
public class Floors implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue
	private Long id;
	private int floorNo;
	private String floorName;
	private String status;
	
	List<FloorWork> floorsWork;
	
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public int getFloorNo() {
		return floorNo;
	}
	public void setFloorNo(int floorNo) {
		this.floorNo = floorNo;
	}
	public String getFloorName() {
		return floorName;
	}
	public void setFloorName(String floorName) {
		this.floorName = floorName;
	}
	public String getStatus() {
		return status;
	}
	public void setStatus(String status) {
		this.status = status;
	}
	
	public List<FloorWork> getFloorsWork() {
		return floorsWork;
	}
	public void setFloorsWork(List<FloorWork> floorsWork) {
		this.floorsWork = floorsWork;
	}
	@Override
	public String toString() {
		return "Floors [id=" + id + ", floorNo=" + floorNo + ", floorName=" + floorName + ", status=" + status + "]";
	}
	
	
}
