package com.gcs.ophwc.services.persistance.dao.entity;
// Generated Jun 6, 2018 7:17:41 PM by Hibernate Tools 5.2.6.Final

import javax.persistence.GeneratedValue;
import javax.persistence.Id;

/**
 * ProjectResources generated by hbm2java
 */
public class ProjectResources implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue
	private Long id;
	private Projects projects;
	private User user;
	private NatureOfWork natureOfProject;
	private String status;

	public ProjectResources() {
	}

	public ProjectResources(Projects projects, User user, String status) {
		this.projects = projects;
		this.user = user;
		this.status = status;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Projects getProjects() {
		return this.projects;
	}

	public void setProjects(Projects projects) {
		this.projects = projects;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}
	

	public NatureOfWork getNatureOfProject() {
		return natureOfProject;
	}

	public void setNatureOfProject(NatureOfWork natureOfProject) {
		this.natureOfProject = natureOfProject;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Override
	public String toString() {
		return "ProjectResources [id=" + id + ", projects=" + projects + ", user=" + user + ", natureOfProject="
				+ natureOfProject + ", status=" + status + "]";
	}

}
