package com.gcs.ophwc.services.persistance.dao.entity;
// Generated Jun 6, 2018 7:17:41 PM by Hibernate Tools 5.2.6.Final

import java.util.Arrays;
import java.util.Date;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;

/**
 * Projects generated by hbm2java
 */
public class Projects implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9103886532161176413L;
	@Id
	@GeneratedValue
	private Long id;
	private String clientName;
	private Divisions divisions;
	private User createdUser;
	private User assignTo;
	private NatureOfWork natureOfProject;
	private String projectName;
	private String projectDefination;
	private String projectLocation;
	private String latitude;
	private String langitude;
	private String status;
	private byte[] projectLogo;
	private String amount;
	private String comments;
	private String isHandovered;

	private String[] imagesPaths;
	private Date lastUpdated;

	public Projects() {
	}

	public Projects(Divisions divisions, User createdUser, String projectName, String projectLocation, String latitude,
			String langitude, String status) {
		this.divisions = divisions;
		this.createdUser = createdUser;
		this.projectName = projectName;
		this.projectLocation = projectLocation;
		this.latitude = latitude;
		this.langitude = langitude;
		this.status = status;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getClientName() {
		return clientName;
	}

	public void setClientName(String clientName) {
		this.clientName = clientName;
	}

	public Divisions getDivisions() {
		return this.divisions;
	}

	public void setDivisions(Divisions divisions) {
		this.divisions = divisions;
	}

	public User getAssignTo() {
		return assignTo;
	}

	public void setAssignTo(User assignTo) {
		this.assignTo = assignTo;
	}

	public NatureOfWork getNatureOfProject() {
		return natureOfProject;
	}

	public void setNatureOfProject(NatureOfWork natureOfProject) {
		this.natureOfProject = natureOfProject;
	}

	public String getProjectDefination() {
		return projectDefination;
	}

	public void setProjectDefination(String projectDefination) {
		this.projectDefination = projectDefination;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public String getProjectLocation() {
		return this.projectLocation;
	}

	public void setProjectLocation(String projectLocation) {
		this.projectLocation = projectLocation;
	}

	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	public String getLangitude() {
		return this.langitude;
	}

	public void setLangitude(String langitude) {
		this.langitude = langitude;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getAmount() {
		return amount;
	}

	public void setAmount(String amount) {
		this.amount = amount;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public String getIsHandovered() {
		return isHandovered;
	}

	public void setIsHandovered(String isHandovered) {
		this.isHandovered = isHandovered;
	}

	public User getCreatedUser() {
		return createdUser;
	}

	public void setCreatedUser(User createdUser) {
		this.createdUser = createdUser;
	}

	public byte[] getProjectLogo() {
		return projectLogo;
	}

	public void setProjectLogo(byte[] projectLogo) {
		this.projectLogo = projectLogo;
	}

	public String[] getImagesPaths() {
		return imagesPaths;
	}

	public void setImagesPaths(String[] imagesPaths) {
		this.imagesPaths = imagesPaths;
	}

	public Date getLastUpdated() {
		return lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@Override
	public String toString() {
		return "Projects [id=" + id + ", clientName=" + clientName + ", divisions=" + divisions + ", createdUser="
				+ createdUser + ", assignTo=" + assignTo + ", natureOfProject=" + natureOfProject + ", projectName="
				+ projectName + ", projectDefination=" + projectDefination + ", projectLocation=" + projectLocation
				+ ", latitude=" + latitude + ", langitude=" + langitude + ", status=" + status + ", projectLogo="
				+ Arrays.toString(projectLogo) + ", amount=" + amount + ", comments=" + comments + ", imagesPaths="
				+ Arrays.toString(imagesPaths) + ", lastUpdated=" + lastUpdated + "]";
	}

}
