package com.gcs.ophwc.services.persistance.dao.entity;
// Generated Jun 6, 2018 7:17:41 PM by Hibernate Tools 5.2.6.Final

import java.util.Date;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SiteVisit generated by hbm2java
 */
public class SiteVisit implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue
	private Long id;
	private ProjectStatus projectStatus;
	private Projects projects;
	private User user;
	private byte[] image;
	private String comments;
	private String latitude;
	private String langitude;
	private String constructionPercentage;
	
	private String imagePath;
	public String getLatitude() {
		return latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	public String getLangitude() {
		return langitude;
	}

	public void setLangitude(String langitude) {
		this.langitude = langitude;
	}

	@Temporal(TemporalType.TIMESTAMP)
	private Date createdDate;
	

	public SiteVisit() {
	}

	public SiteVisit(ProjectStatus projectStatus, Projects projects, User user) {
		this.projectStatus = projectStatus;
		this.projects = projects;
		this.user = user;
	}

	public SiteVisit(ProjectStatus projectStatus, Projects projects, User user, byte[] image, String comments,
			Date createdDate) {
		this.projectStatus = projectStatus;
		this.projects = projects;
		this.user = user;
		this.image = image;
		this.comments = comments;
		this.createdDate = createdDate;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public ProjectStatus getProjectStatus() {
		return this.projectStatus;
	}

	public void setProjectStatus(ProjectStatus projectStatus) {
		this.projectStatus = projectStatus;
	}

	public Projects getProjects() {
		return this.projects;
	}

	public void setProjects(Projects projects) {
		this.projects = projects;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	
	

	public String getConstructionPercentage() {
		return constructionPercentage;
	}

	public void setConstructionPercentage(String constructionPercentage) {
		this.constructionPercentage = constructionPercentage;
	}

	public String getImagePath() {
		return imagePath;
	}

	public void setImagePath(String imagePath) {
		this.imagePath = imagePath;
	}

}
