package com.gcs.ophwc.services.persistance.dao.entity;
// Generated Jun 6, 2018 7:17:41 PM by Hibernate Tools 5.2.6.Final

import java.util.Arrays;
import java.util.List;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue
	private Long id;
	private Divisions divisions;
	private UserTypes userTypes;
	private String username;
	private String password;
	private String firstName;
	private String lastName;
	private String phoneNum;
	private String emailId;
	private byte[] userImage;
	private String status;
	
	private List<NatureOfWork> natureList;
	private List<Projects> projList;
	
	private String projName;

	public User() {
	}

	public User(Divisions divisions, UserTypes userTypes, String username, String password, String status) {
		this.divisions = divisions;
		this.userTypes = userTypes;
		this.username = username;
		this.password = password;
		this.status = status;
	}

	public User(Divisions divisions, UserTypes userTypes, String username, String password, String firstName,
			String lastName, String phoneNum, String emailId, byte[] userImage, String status) {
		this.divisions = divisions;
		this.userTypes = userTypes;
		this.username = username;
		this.password = password;
		this.firstName = firstName;
		this.lastName = lastName;
		this.phoneNum = phoneNum;
		this.emailId = emailId;
		this.userImage = userImage;
		this.status = status;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Divisions getDivisions() {
		return this.divisions;
	}

	public void setDivisions(Divisions divisions) {
		this.divisions = divisions;
	}

	public UserTypes getUserTypes() {
		return this.userTypes;
	}

	public void setUserTypes(UserTypes userTypes) {
		this.userTypes = userTypes;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getPhoneNum() {
		return this.phoneNum;
	}

	public void setPhoneNum(String phoneNum) {
		this.phoneNum = phoneNum;
	}

	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	public byte[] getUserImage() {
		return this.userImage;
	}

	public void setUserImage(byte[] userImage) {
		this.userImage = userImage;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	
	public List<NatureOfWork> getNatureList() {
		return natureList;
	}

	public void setNatureList(List<NatureOfWork> natureList) {
		this.natureList = natureList;
	}

	public List<Projects> getProjList() {
		return projList;
	}

	public void setProjList(List<Projects> projList) {
		this.projList = projList;
	}
	

	public String getProjName() {
		return projName;
	}

	public void setProjName(String projName) {
		this.projName = projName;
	}

	@Override
	public String toString() {
		return "User [id=" + id + ", divisions=" + divisions + ", userTypes=" + userTypes + ", username=" + username
				+ ", password=" + password + ", firstName=" + firstName + ", lastName=" + lastName + ", phoneNum="
				+ phoneNum + ", emailId=" + emailId + ", userImage=" + Arrays.toString(userImage) + ", status=" + status
				+ "]";
	}
	
	

}
