package com.gcs.ophwc.services.persistance.dao.entity;
// Generated Jun 6, 2018 7:17:41 PM by Hibernate Tools 5.2.6.Final

import java.util.Date;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;

/**
 * VideoCallHistory generated by hbm2java
 */
public class VideoCallHistory implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue
	private Long id;
	private User user;
	private String calledToNumber;
	private String duration;
	private Date createdDate;

	public VideoCallHistory() {
	}

	public VideoCallHistory(User user, String calledToNumber, String duration, Date createdDate) {
		this.user = user;
		this.calledToNumber = calledToNumber;
		this.duration = duration;
		this.createdDate = createdDate;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getCalledToNumber() {
		return this.calledToNumber;
	}

	public void setCalledToNumber(String calledToNumber) {
		this.calledToNumber = calledToNumber;
	}

	public String getDuration() {
		return this.duration;
	}

	public void setDuration(String duration) {
		this.duration = duration;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

}
